# Generated by Django 6.0.3 on 2026-04-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='gneder',
            new_name='gender',
        ),
    ]
