# Generated by Django 6.0.3 on 2026-04-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('NG', 'Not Given'), ('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
